  # HTML Head #
  author: betulgundogdu
  title: tofi
  description: tofi jekyll personal blog theme
  keywords: blog, personal, jekyll, theme

  #Social Buttons
  social:
    - title: "github"
      url: "https://github.com/betulgundogdu"
    - title: "leetcode"
      url: "https://leetcode.com/deathQueue/"
    - title: "codepen"
      url: "https://codepen.io/ihpwtnp"
    - title: "linkedin"
      url: "https://www.linkedin.com/in/betulgundogdu/"

  # Minification scss 
  sass:
    sass_dir:          _scss
    style:            :compressed
    
